+mkdir frame function

diff --git a/gtd b/gtd
--- a/gtd
+++ b/gtd
@@ -291,6 +291,34 @@ gtd_init() {
 		  "to refer GTD working directory."
 	fi
 }
+#=== Mkdir =====================================================================
+usage_mkdir() {
+	cat<<-EOF
+Usage: gtd mkdir [OPTION]...
+   or: gtd mkdir [OPTION]...
+Description
+
+Options:
+  -o, --option=VALUE  Meaning
+	EOF
+}
+
+gtd_mkdir() {
+	local TEMP=`getopt -o ab: --long apple,banana: \
+	  -n 'gtd.mkdir' -- "$@"`
+	[ $? != 0 ] && echo "Failed parsing the arguments." && return
+	eval set -- "$TEMP"
+	debug "gtd_mkdir($@)"
+	local apple=false; local banana=""
+	while : ; do
+		case "$1" in
+		-a|--apple) apple=true; shift;;
+		-b|--banana) banana="$2"; shift 2;;
+		--) shift; break;;
+		*) echo "Unknown option: $1"; return;;
+		esac
+	done
+}
 #=== ADD =======================================================================
 usage_add() {
 	cat<<-EOF
@@ -310,6 +338,7 @@ gtd_add() {
 	  -n 'gtd.add' -- "$@"`
 	[ $? != 0 ] && echo "Failed parsing the arguments." && return
 	eval set -- "$TEMP"
+	debug "gtd_add($@)"
 	local path=""; local message=""; local template=""
 	local time=""; local editor=""
 	while : ; do
@@ -390,6 +419,7 @@ gtd_move() {
 	  -n 'gtd.move' -- "$@"`
 	[ $? != 0 ] && echo "Failed parsing the arguments." && return
 	eval set -- "$TEMP"
+	debug "gtd_move($@)"
 	local target=""
 	local source=()
 	while : ; do
@@ -445,6 +475,7 @@ gtd_list() {
 	  -n 'gtd.list' -- "$@"`
 	[ $? != 0 ] && echo "Failed parsing the arguments." && return
 	eval set -- "$TEMP"
+	debug "gtd_list($@)"
 	apple=false; banana=""
 	while : ; do
 		case "$1" in
@@ -513,6 +544,7 @@ gtd_edit() {
 	  -n 'gtd.edit' -- "$@"`
 	[ $? != 0 ] && echo "Failed parsing the arguments." && return
 	eval set -- "$TEMP"
+	debug "gtd_edit($@)"
 	local editor=""
 	while : ; do
 		case "$1" in
@@ -552,6 +584,7 @@ gtd_test() {
 	TEMP=`getopt -o t: --long task: -n 'gtd.test' -- "$@"`
 	[ $? != 0 ] && echo "Failed parsing the arguments." && return
 	eval set -- "$TEMP"
+	debug "gtd_test($@)"
 	local task=""
 	while : ; do
 		case "$1" in
@@ -579,6 +612,7 @@ process_command() {
 	init) [ $help_me == true ] && usage_init || gtd_init;;
 	ps1) gtd_ps1;;
 	config) [ $help_me == true ] && usage_config || vim "$GTD_ROOT/.gtdrc";;
+	md|mkdir) shift; [ $help_me == true ] && usage_mkdir || gtd_mkdir "$@";;
 	a|add) shift; [ $help_me == true ] && usage_add || gtd_add "$@";;
 	m|mv|move) shift; [ $help_me == true ] && usage_move || gtd_move "$@";;
 	l|ls|list) shift; [ $help_me == true ] && usage_list || gtd_list "$@";;
@@ -658,6 +692,7 @@ gtd_template() {
 	  -n 'gtd.template' -- "$@"`
 	[ $? != 0 ] && echo "Failed parsing the arguments." && return
 	eval set -- "$TEMP"
+	debug "gtd_template($@)"
 	local apple=false; local banana=""
 	while : ; do
 		case "$1" in
